const DEFAULT_SOURCE_META = {
  type: "rss",
  categoryHint: "general",
  categoryHints: ["general"],
  priority: 40,
  sourceGroup: "general",
  forPersonal: false,
  official: false,
  specialist: false,
  sourceTags: [],
};

function source(definition) {
  const categoryHints = Array.isArray(definition.categoryHints) && definition.categoryHints.length
    ? [...new Set(definition.categoryHints.filter(Boolean))]
    : [definition.categoryHint ?? DEFAULT_SOURCE_META.categoryHint];
  return {
    ...DEFAULT_SOURCE_META,
    ...definition,
    categoryHint: definition.categoryHint ?? categoryHints[0] ?? DEFAULT_SOURCE_META.categoryHint,
    categoryHints,
    sourceTags: Array.isArray(definition.sourceTags) ? [...new Set(definition.sourceTags.filter(Boolean))] : [],
  };
}

export const RSS_FEEDS = [
  source({
    id: "yahoo-top",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース",
    url: "https://news.yahoo.co.jp/rss/topics/top-picks.xml",
    categoryHints: ["general"],
    priority: 82,
    sourceGroup: "important-news",
  }),
  source({
    id: "yahoo-domestic",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / 国内",
    url: "https://news.yahoo.co.jp/rss/topics/domestic.xml",
    categoryHints: ["general"],
    priority: 76,
    sourceGroup: "important-news",
  }),
  source({
    id: "yahoo-world",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / 国際",
    url: "https://news.yahoo.co.jp/rss/topics/world.xml",
    categoryHints: ["world"],
    priority: 78,
    sourceGroup: "important-news",
  }),
  source({
    id: "yahoo-business",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / 経済",
    url: "https://news.yahoo.co.jp/rss/topics/business.xml",
    categoryHints: ["business"],
    priority: 78,
    sourceGroup: "important-news",
  }),
  source({
    id: "yahoo-entertainment",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / エンタメ",
    url: "https://news.yahoo.co.jp/rss/topics/entertainment.xml",
    categoryHints: ["entertainment"],
    priority: 66,
    sourceGroup: "general-entertainment",
  }),
  source({
    id: "yahoo-sports",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / スポーツ",
    url: "https://news.yahoo.co.jp/rss/topics/sports.xml",
    categoryHints: ["sports"],
    priority: 58,
    sourceGroup: "general-sports",
  }),
  source({
    id: "yahoo-it",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / IT",
    url: "https://news.yahoo.co.jp/rss/topics/it.xml",
    categoryHints: ["tech"],
    priority: 62,
    sourceGroup: "general-tech",
  }),
  source({
    id: "yahoo-science",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / 科学",
    url: "https://news.yahoo.co.jp/rss/topics/science.xml",
    categoryHints: ["tech"],
    priority: 60,
    sourceGroup: "general-tech",
  }),
  source({
    id: "yahoo-local",
    source: "Yahoo!ニュース",
    sourceName: "Yahoo!ニュース / 地域",
    url: "https://news.yahoo.co.jp/rss/topics/local.xml",
    categoryHints: ["general"],
    priority: 50,
    sourceGroup: "local-news",
  }),
  source({
    id: "nhk-top",
    source: "NHK RSS",
    sourceName: "NHK",
    url: "https://www3.nhk.or.jp/rss/news/cat0.xml",
    categoryHints: ["general", "world", "business", "politics"],
    priority: 92,
    sourceGroup: "important-news",
    official: true,
  }),
  source({
    id: "bbc-world",
    source: "BBC",
    sourceName: "BBC World",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    categoryHints: ["world"],
    priority: 72,
    sourceGroup: "important-news",
  }),
  source({
    id: "bbc-business",
    source: "BBC",
    sourceName: "BBC Business",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    categoryHints: ["business", "world"],
    priority: 70,
    sourceGroup: "important-news",
  }),

  source({
    id: "automaton",
    source: "AUTOMATON",
    sourceName: "AUTOMATON",
    url: "https://automaton-media.com/feed/",
    categoryHints: ["games"],
    priority: 96,
    sourceGroup: "games",
    specialist: true,
    forPersonal: true,
    sourceTags: ["games", "steam", "switch", "pc"],
  }),
  source({
    id: "gamespark",
    source: "Game*Spark",
    sourceName: "Game*Spark",
    url: "https://www.gamespark.jp/rss/index.rdf",
    categoryHints: ["games"],
    priority: 92,
    sourceGroup: "games",
    specialist: true,
    forPersonal: true,
    sourceTags: ["games", "pc", "console"],
  }),
  source({
    id: "inside",
    source: "INSIDE",
    sourceName: "INSIDE",
    url: "https://www.inside-games.jp/rss/index.rdf",
    categoryHints: ["games"],
    priority: 90,
    sourceGroup: "games",
    specialist: true,
    forPersonal: true,
    sourceTags: ["games", "nintendo", "switch", "pokemon"],
  }),
  source({
    id: "famitsu",
    source: "ファミ通",
    sourceName: "ファミ通",
    url: "https://www.famitsu.com/rss/famitsu/common/",
    categoryHints: ["games"],
    priority: 94,
    sourceGroup: "games",
    specialist: true,
    forPersonal: true,
    sourceTags: ["games", "nintendo", "switch", "pokemon"],
  }),
  source({
    id: "4gamer",
    source: "4Gamer",
    sourceName: "4Gamer",
    url: "https://www.4gamer.net/rss/index.xml",
    categoryHints: ["games"],
    priority: 94,
    sourceGroup: "games",
    specialist: true,
    forPersonal: true,
    sourceTags: ["games", "pc", "console", "steam"],
  }),
  source({
    id: "denfami",
    source: "電ファミニコゲーマー",
    sourceName: "電ファミニコゲーマー",
    url: "https://news.denfaminicogamer.jp/feed",
    categoryHints: ["games", "net-culture"],
    priority: 92,
    sourceGroup: "games",
    specialist: true,
    forPersonal: true,
    sourceTags: ["games", "net-culture", "otaku"],
  }),
  source({
    id: "steam-news",
    source: "Steam",
    sourceName: "Steam News",
    url: "https://store.steampowered.com/feeds/news.xml",
    categoryHints: ["games"],
    priority: 88,
    sourceGroup: "steam",
    specialist: true,
    official: true,
    forPersonal: true,
    sourceTags: ["games", "steam", "official"],
  }),
  source({
    id: "steam-specials",
    source: "Steam",
    sourceName: "Steam Specials",
    url: "https://store.steampowered.com/feeds/specials.xml",
    categoryHints: ["games"],
    priority: 88,
    sourceGroup: "sales",
    specialist: true,
    official: true,
    forPersonal: true,
    sourceTags: ["games", "steam", "sale", "deals", "official"],
  }),

  source({
    id: "animeanime",
    source: "アニメ！アニメ！",
    sourceName: "アニメ！アニメ！",
    url: "https://animeanime.jp/rss/index.rdf",
    categoryHints: ["entertainment", "manga"],
    priority: 92,
    sourceGroup: "anime",
    specialist: true,
    forPersonal: true,
    sourceTags: ["anime", "manga", "voice-actor", "movie"],
  }),
  source({
    id: "mantanweb",
    source: "MANTANWEB",
    sourceName: "MANTANWEB",
    url: "https://mantan-web.jp/index.rss",
    categoryHints: ["entertainment", "manga"],
    priority: 84,
    sourceGroup: "anime",
    specialist: true,
    forPersonal: true,
    sourceTags: ["anime", "manga", "entertainment"],
  }),
  source({
    id: "comic-natalie",
    source: "コミックナタリー",
    sourceName: "コミックナタリー",
    url: "https://natalie.mu/comic/rss",
    categoryHints: ["manga", "entertainment"],
    priority: 92,
    sourceGroup: "anime",
    specialist: true,
    forPersonal: true,
    sourceTags: ["manga", "anime", "otaku"],
  }),
  source({
    id: "animatetimes",
    source: "アニメイトタイムズ",
    sourceName: "アニメイトタイムズ",
    url: "https://www.animatetimes.com/rss.php",
    categoryHints: ["entertainment", "manga"],
    priority: 88,
    sourceGroup: "anime",
    specialist: true,
    forPersonal: true,
    sourceTags: ["anime", "manga", "event", "collabo-cafe"],
  }),
  source({
    id: "pokemon-official",
    source: "ポケモン公式",
    sourceName: "ポケモン公式",
    url: "https://www.pokemon.co.jp/rss/index.xml",
    categoryHints: ["games"],
    priority: 98,
    sourceGroup: "pokemon",
    specialist: true,
    official: true,
    forPersonal: true,
    sourceTags: ["pokemon", "official", "games"],
  }),

  source({
    id: "itmedia-news",
    source: "ITmedia",
    sourceName: "ITmedia NEWS",
    url: "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml",
    categoryHints: ["tech", "sns", "net-culture"],
    priority: 74,
    sourceGroup: "net-culture",
    specialist: true,
    forPersonal: true,
    sourceTags: ["net-culture", "sns", "tech"],
  }),
  source({
    id: "itmedia-all",
    source: "ITmedia",
    sourceName: "ITmedia",
    url: "https://rss.itmedia.co.jp/rss/2.0/itmedia_all.xml",
    categoryHints: ["tech", "sns", "net-culture"],
    priority: 68,
    sourceGroup: "net-culture",
    specialist: true,
    forPersonal: true,
    sourceTags: ["net-culture", "sns", "tech"],
  }),
  source({
    id: "jcast",
    source: "J-CASTニュース",
    sourceName: "J-CASTニュース",
    url: "https://www.j-cast.com/index.xml",
    categoryHints: ["sns", "net-culture", "general"],
    priority: 72,
    sourceGroup: "net-culture",
    specialist: true,
    forPersonal: true,
    sourceTags: ["net-culture", "sns", "buzz"],
  }),
  source({
    id: "netorabo",
    source: "ねとらぼ",
    sourceName: "ねとらぼ",
    url: "https://nlab.itmedia.co.jp/rss/index.rdf",
    categoryHints: ["sns", "net-culture", "entertainment"],
    priority: 84,
    sourceGroup: "net-culture",
    specialist: true,
    forPersonal: true,
    sourceTags: ["net-culture", "sns", "buzz", "otaku"],
  }),
  source({
    id: "kai-you",
    source: "KAI-YOU",
    sourceName: "KAI-YOU",
    url: "https://kai-you.net/contents/feed.rss",
    categoryHints: ["sns", "net-culture", "entertainment"],
    priority: 90,
    sourceGroup: "net-culture",
    specialist: true,
    forPersonal: true,
    sourceTags: ["net-culture", "sns", "meme", "otaku"],
  }),
  source({
    id: "hatena-hotentry",
    source: "はてなブックマーク",
    sourceName: "はてなブックマーク人気",
    url: "https://b.hatena.ne.jp/hotentry.rss",
    categoryHints: ["sns", "net-culture"],
    priority: 74,
    sourceGroup: "net-culture",
    specialist: true,
    forPersonal: true,
    sourceTags: ["net-culture", "sns", "trend", "buzz"],
  }),
  source({
    id: "scrap-magazine",
    source: "SCRAP",
    sourceName: "SCRAP",
    url: "https://www.scrapmagazine.com/feed/",
    categoryHints: ["entertainment"],
    priority: 94,
    sourceGroup: "events",
    specialist: true,
    official: true,
    forPersonal: true,
    sourceTags: ["event", "escape-game", "nazotoki", "immersive", "tokyo"],
  }),
  source({
    id: "realdgame",
    source: "リアル脱出ゲーム",
    sourceName: "リアル脱出ゲーム",
    url: "https://realdgame.jp/feed/",
    categoryHints: ["entertainment"],
    priority: 96,
    sourceGroup: "events",
    specialist: true,
    official: true,
    forPersonal: true,
    sourceTags: ["event", "escape-game", "nazotoki", "scrap", "tokyo"],
  }),
  source({
    id: "event-checker",
    source: "Event Checker",
    sourceName: "Event Checker",
    url: "https://event-checker.info/feed/",
    categoryHints: ["entertainment", "general"],
    priority: 82,
    sourceGroup: "events",
    specialist: true,
    forPersonal: true,
    sourceTags: ["event", "tokyo", "popup", "exhibition"],
  }),
  source({
    id: "collabo-cafe",
    source: "コラボカフェ",
    sourceName: "コラボカフェ",
    url: "https://collabo-cafe.com/feed/",
    categoryHints: ["entertainment", "manga"],
    priority: 90,
    sourceGroup: "events",
    specialist: true,
    forPersonal: true,
    sourceTags: ["event", "collabo-cafe", "anime", "manga", "popup"],
  }),

  source({
    id: "google-news-pokemon",
    source: "Google News",
    sourceName: "Google News / ポケモン",
    url: buildGoogleNewsRssUrl("ポケモン OR ポケカ OR Pokemon GO OR Pokémon HOME"),
    categoryHints: ["games"],
    priority: 36,
    sourceGroup: "google-news",
    forPersonal: true,
    sourceTags: ["pokemon", "games"],
  }),
  source({
    id: "google-news-games",
    source: "Google News",
    sourceName: "Google News / ゲーム",
    url: buildGoogleNewsRssUrl("ゲーム OR 任天堂 OR Nintendo OR Switch OR Steam OR PS5"),
    categoryHints: ["games"],
    priority: 34,
    sourceGroup: "google-news",
    forPersonal: true,
    sourceTags: ["games", "switch", "steam"],
  }),
  source({
    id: "google-news-manga-anime",
    source: "Google News",
    sourceName: "Google News / 漫画・アニメ",
    url: buildGoogleNewsRssUrl("漫画 OR マンガ OR アニメ OR 映画化 OR アニメ化"),
    categoryHints: ["manga", "entertainment"],
    priority: 34,
    sourceGroup: "google-news",
    forPersonal: true,
    sourceTags: ["manga", "anime"],
  }),
  source({
    id: "google-news-net-culture",
    source: "Google News",
    sourceName: "Google News / ネット話題",
    url: buildGoogleNewsRssUrl("SNS OR ネットカルチャー OR バズ OR 炎上 OR ミーム"),
    categoryHints: ["sns", "net-culture"],
    priority: 32,
    sourceGroup: "google-news",
    forPersonal: true,
    sourceTags: ["sns", "net-culture", "buzz", "meme"],
  }),
  source({
    id: "google-news-sales",
    source: "Google News",
    sourceName: "Google News / セール",
    url: buildGoogleNewsRssUrl("Steam セール OR Nintendo セール OR Amazon セール OR 楽天 セール"),
    categoryHints: ["games"],
    priority: 32,
    sourceGroup: "google-news",
    forPersonal: true,
    sourceTags: ["sale", "deals", "steam", "nintendo"],
  }),
  source({
    id: "google-news-escape-immersive",
    source: "Google News",
    sourceName: "Google News / 脱出ゲーム・イマーシブ",
    url: buildGoogleNewsRssUrl("脱出ゲーム OR リアル脱出ゲーム OR SCRAP OR 謎解き OR イマーシブ OR イマーシブフォート OR 体験型イベント OR 展示会 OR コラボカフェ"),
    categoryHints: ["entertainment"],
    priority: 30,
    sourceGroup: "google-news",
    forPersonal: true,
    sourceTags: ["event", "escape-game", "nazotoki", "immersive", "collabo-cafe"],
  }),
  source({
    id: "google-news-tech",
    source: "Google News",
    sourceName: "Google News / テック",
    url: buildGoogleNewsRssUrl("テクノロジー OR AI OR 生成AI OR 半導体 OR OpenAI"),
    categoryHints: ["tech"],
    priority: 34,
    sourceGroup: "google-news",
    sourceTags: ["tech", "ai"],
  }),
  source({
    id: "google-news-business",
    source: "Google News",
    sourceName: "Google News / 経済",
    url: buildGoogleNewsRssUrl("経済 OR 企業 OR 決算 OR 投資 OR 株"),
    categoryHints: ["business"],
    priority: 34,
    sourceGroup: "google-news",
    sourceTags: ["business"],
  }),
  source({
    id: "google-news-politics",
    source: "Google News",
    sourceName: "Google News / 政治",
    url: buildGoogleNewsRssUrl("政治 OR 国会 OR 首相 OR 選挙 OR 与党 OR 野党"),
    categoryHints: ["politics"],
    priority: 34,
    sourceGroup: "google-news",
    sourceTags: ["politics"],
  }),
  source({
    id: "google-news-world",
    source: "Google News",
    sourceName: "Google News / 国際",
    url: buildGoogleNewsRssUrl("国際 OR 海外 OR 外交 OR 戦況 OR 米国"),
    categoryHints: ["world"],
    priority: 34,
    sourceGroup: "google-news",
    sourceTags: ["world"],
  }),
  source({
    id: "google-news-crime",
    source: "Google News",
    sourceName: "Google News / 犯罪・事件",
    url: buildGoogleNewsRssUrl("事件 OR 逮捕 OR 送検 OR 殺人 OR 強盗 OR 詐欺"),
    categoryHints: ["crime"],
    priority: 34,
    sourceGroup: "google-news",
    sourceTags: ["crime"],
  }),
  source({
    id: "google-news-sports",
    source: "Google News",
    sourceName: "Google News / スポーツ",
    url: buildGoogleNewsRssUrl("スポーツ OR 野球 OR サッカー OR 試合 OR 大会"),
    categoryHints: ["sports"],
    priority: 28,
    sourceGroup: "google-news",
    sourceTags: ["sports"],
  }),
  source({
    id: "google-news-adult",
    source: "Google News",
    sourceName: "Google News / アダルト",
    url: buildGoogleNewsRssUrl("グラビア OR 写真集 OR デジタル写真集 OR グラドル OR 水着 OR ランジェリー OR セクシーショット OR セクシー女優 OR AV女優 OR アダルト"),
    categoryHints: ["adult"],
    priority: 36,
    sourceGroup: "google-news",
    sourceTags: ["adult", "gravure", "photo-book"],
  }),
  source({
    id: "google-news-gravure",
    source: "Google News",
    sourceName: "Google News / グラビア・写真集",
    url: buildGoogleNewsRssUrl("グラビア OR 写真集 OR デジタル写真集 OR グラドル OR 水着姿 OR ランジェリー OR セクシーショット"),
    categoryHints: ["adult", "entertainment"],
    priority: 38,
    sourceGroup: "google-news",
    sourceTags: ["adult", "gravure", "entertainment", "photo-book"],
  }),
  source({
    id: "google-news-fanza-dlsite",
    source: "Google News",
    sourceName: "Google News / FANZA・DLsite",
    url: buildGoogleNewsRssUrl("FANZA OR DLsite OR DMM OR 同人 セール OR アダルト キャンペーン OR 割引"),
    categoryHints: ["adult"],
    priority: 30,
    sourceGroup: "google-news",
    sourceTags: ["adult", "sale", "doujin"],
  }),
];

function buildGoogleNewsRssUrl(query) {
  return `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=ja&gl=JP&ceid=JP:ja`;
}
